set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_periph/periph_clk.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_periph/periph_rst_in.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_periph/button_pio.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_periph/dipsw_pio.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_periph/led_pio.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_periph/ILC.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_periph/pb_cpu_0.ip
set_global_assignment -name QSYS_FILE ../../src/rtile_4x4/qsys/subsys_periph.qsys
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_jtg_mst/jtag_clk.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_jtg_mst/jtag_rst_in.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_jtg_mst/hps_m.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_jtg_mst/fpga_m.ip
set_global_assignment -name QSYS_FILE ../../src/rtile_4x4/qsys/subsys_jtg_mst.qsys
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/clk_100.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/rst_in.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/user_rst_clkgate_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/sysid.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/ocm.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/fpga_m2ocm_pb.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/agilex_hps.ip
#set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/emif_hps.ip
#set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/emif_calbus_0.ip
set_global_assignment -name QSYS_FILE ../../src/rtile_4x4/qsys/qsys_top.qsys
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/qsys_top_iopll_0.ip
set_global_assignment -name QSYS_FILE ../../src/rtile_4x4/qsys/subsys_pcie.qsys
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/qsys_top_clock_bridge_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/qsys_top_reset_bridge_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/qsys_top_clock_bridge_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/qsys_top_reset_bridge_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_jtg_mst/subsys_jtg_mst_clock_bridge_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_jtg_mst/subsys_jtg_mst_reset_bridge_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/qsys_top_mm_ccb_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_reset_bridge_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_reset_bridge_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_clock_bridge_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_clock_bridge_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_config_timeout_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_reset_bridge_2.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_f2h_interface_tester_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_address_span_extender_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_performance_counter_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_address_span_extender_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_mm_ccb_3.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_mm_ccb_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_clock_bridge_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_mm_ccb_2.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_mm_ccb_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_msi_to_gic_gen_0.ip
#set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_systemclk_f_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_mm_ccb_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_mm_ccb_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_mm_bridge_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_mm_bridge_2.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_mm_bridge_5.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_mm_bridge_4.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_mm_bridge_7.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_subsystem_mm_bridge_6.ip
#set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_intel_pcie_ftile_mcdma_dev_1.ip
#set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_intel_pcie_ftile_mcdma_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/qsys_top/qsys_top_intel_cache_coherency_translator_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/qsys/ip/qsys_top/qsys_top_emif_hps_ph2_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/qsys/ip/qsys_top/qsys_top_intel_noc_clock_ctrl_0.ip

set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_intel_pcie_rtile_mcdma_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/subsys_pcie_address_remapper_0.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_address_extender_6gb_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_mm_ccb_6gb_1.ip
set_global_assignment -name IP_FILE ../../src/rtile_4x4/ip/subsys_pcie/Pcie_rp_mm_bridge_6gb_1.ip